INSERT INTO port (FILE_NAME,REMARK,USER_ID,DEPT_ID,PRIV_ID,STATUS,MODULE_NO,MODULE_POS,VIEW_TYPE,MODULE_LINES,MODULE_SCROLL) VALUES 
 ('待办公文.js',NULL,NULL,'0',NULL,0,NULL,NULL,'1',5,'0');
 
 
CREATE TABLE FLOW_TIMER (
  SEQ_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FLOW_ID INTEGER UNSIGNED NOT NULL,
  TYPE VARCHAR(45),
  USER_STR TEXT,
  REMIND_DATE VARCHAR(45),
  REMIND_TIME  VARCHAR(45),
  LAST_TIME DATETIME,
  PRIMARY KEY (SEQ_ID)
);
ALTER TABLE sys_log MODIFY COLUMN SEQ_ID INT(20) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE vote_title ADD COLUMN SUBJECT_FONT text;
ALTER TABLE notify ADD COLUMN subject_Font text;
ALTER TABLE news ADD COLUMN subject_Font text;
ALTER TABLE ds_field ADD COLUMN FK_NAME_FIELD_NO2 VARCHAR(45) AFTER IS_PRIMARY_KEY;
ALTER TABLE person MODIFY COLUMN CANBROADCAST INT(11) DEFAULT 50;
update person set CANBROADCAST = 50;

INSERT INTO ds_field (TABLE_NO,FIELD_NO,FIELD_NAME,PROP_NAME,FIELD_DESC,FK_TABLE_NO,FK_TABLE_NO2,FK_RELA_FIELD_NO,FK_NAME_FIELD_NO,FK_FILTER,CODE_CLASS,DEFAULT_VALUE,FORMAT_MODE,FORMAT_RULE,ERROR_MSRG,FIELD_PRECISION,FIELD_SCALE,DATA_TYPE,IS_IDENTITY,DISPLAY_LEN,IS_MUST_FILL,IS_PRIMARY_KEY) VALUES ('11116','11116079','IM_RANGE','imRange','IM_RANGE','','','','','','','','number','','',11,0,4,'0',0,'0','0');