CREATE TABLE `t9`.`SYS_TABLE` (
  `SEQ_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `TABLE_NAME` VARCHAR(45) NOT NULL,
  `NO_FIELD_PRE` VARCHAR(45),
  `NO_FIELD_LENGTH` INTEGER UNSIGNED,
  `NO_FIELD_START` INTEGER UNSIGNED,
  PRIMARY KEY (`SEQ_ID`)
)
ENGINE = InnoDB;

CREATE TABLE `t9`.`SYS_TABLE_FIELD` (
  `SEQ_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `FIELD_NAME` VARCHAR(45) NOT NULL,
  `FIELD_TYPE` VARCHAR(45) NOT NULL,
  `FIELD_LENGTH` INTEGER UNSIGNED NOT NULL,
  `TABLE_ID` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (`SEQ_ID`)
)
ENGINE = InnoDB;
ALTER TABLE `t9`.`sys_table` MODIFY COLUMN `SEQ_ID` INT(10) UNSIGNED NOT NULL,
 MODIFY COLUMN `NO_FIELD_LENGTH` INT(10) UNSIGNED DEFAULT 1,
 MODIFY COLUMN `NO_FIELD_START` INT(10) UNSIGNED DEFAULT 1,
 ADD COLUMN `NO_FIELD_DEFAULT` VARCHAR(45) NOT NULL DEFAULT 1 AFTER `NO_FILED_START`;
