INSERT INTO port (FILE_NAME,REMARK,USER_ID,DEPT_ID,PRIV_ID,STATUS,MODULE_NO,MODULE_POS,VIEW_TYPE,MODULE_LINES,MODULE_SCROLL) VALUES 
 ('待办公文.js',NULL,NULL,'0',NULL,0,NULL,NULL,'1',5,'0');
 
CREATE TABLE FLOW_TIMER (
  SEQ_ID int   NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  FLOW_ID int NOT NULL,
   TYPE  VARCHAR(45),
  USER_STR TEXT,
  REMIND_DATE VARCHAR(45),
  REMIND_TIME VARCHAR(45),
  LAST_TIME datetime
);
alter table vote_title add SUBJECT_FONT TEXT;
alter table notify add SUBJECT_FONT TEXT;
alter table news add SUBJECT_FONT TEXT;
alter table ds_field add FK_NAME_FIELD_NO2 VARCHAR(45);
INSERT INTO ds_field (TABLE_NO,FIELD_NO,FIELD_NAME,PROP_NAME,FIELD_DESC,FK_TABLE_NO,FK_TABLE_NO2,FK_RELA_FIELD_NO,FK_NAME_FIELD_NO,FK_FILTER,CODE_CLASS,DEFAULT_VALUE,FORMAT_MODE,FORMAT_RULE,ERROR_MSRG,FIELD_PRECISION,FIELD_SCALE,DATA_TYPE,IS_IDENTITY,DISPLAY_LEN,IS_MUST_FILL,IS_PRIMARY_KEY,FK_NAME_FIELD_NO2) VALUES ('11116','11116079','IM_RANGE','imRange','IM_RANGE','','','','','','','','number','','',11,0,4,'0',0,'0','0','');

