ALTER TABLE flow_type ADD COLUMN VIEW_USER TEXT ,
 ADD COLUMN VIEW_PRIV INTEGER UNSIGNED ;
ALTER TABLE flow_process ADD COLUMN VIEW_PRIV INTEGER UNSIGNED;
ALTER TABLE flow_run ADD COLUMN VIEW_USER TEXT;

CREATE TABLE APP_LOG (
  SEQ_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID INTEGER UNSIGNED,
  TIME DATETIME,
  MODULE VARCHAR(45),
  OPP_ID VARCHAR(45),
  TYPE VARCHAR(45),
  REMARK MEDIUMINT UNSIGNED,
  PRIMARY KEY (SEQ_ID)
)
ENGINE = InnoDB;
 
