CREATE TABLE `deptnotify` (
  `SEQ_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FROM_DEPT` int(11) DEFAULT '0',
  `FROM_ID` varchar(20) DEFAULT NULL,
  `TO_ID` text,
  `SUBJECT` varchar(200) DEFAULT NULL,
  `CONTENT` text,
  `SEND_TIME` datetime DEFAULT NULL,
  `BEGIN_DATE` datetime DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `ATTACHMENT_ID` text,
  `ATTACHMENT_NAME` text,
  `READERS` text,
  `PRINT` char(1) DEFAULT NULL,
  `PRIV_ID` text,
  `USER_ID` text,
  `TYPE_ID` varchar(200) DEFAULT NULL,
  `TOP` varchar(20) DEFAULT '0',
  `TOP_DAYS` int(11) DEFAULT '0',
  `FORMAT` varchar(20) DEFAULT '0',
  `PUBLISH` char(1) DEFAULT '1',
  `AUDITER` varchar(20) DEFAULT NULL,
  `REASON` text,
  `AUDIT_DATE` datetime DEFAULT NULL,
  `COMPRESS_CONTENT` blob,
  `DOWNLOAD` char(1) DEFAULT NULL,
  `subject_Font` text,
  PRIMARY KEY (`SEQ_ID`),
  UNIQUE KEY `SEQ_ID` (`SEQ_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
