ALTER TABLE rms_file ADD COLUMN PRIV_USER VARCHAR(2000),
    ADD COLUMN PRIV_DEPT VARCHAR(2000) ,
    ADD COLUMN PRIV_ROLE VARCHAR(2000) ;

    ALTER TABLE rms_roll ADD COLUMN PRIV_USER VARCHAR(2000),
    ADD COLUMN PRIV_DEPT VARCHAR(2000) ,
    ADD COLUMN PRIV_ROLE VARCHAR(2000) ;
    
ALTER TABLE flow_form_item ADD COLUMN LV_COLTYPE TEXT ,
 ADD COLUMN LV_COLVALUE TEXT ;
 
 ALTER TABLE flow_process ADD COLUMN CONTROL_MODE VARCHAR(2000) ;
 

