ALTER TABLE flow_type ADD  VIEW_USER  VARCHAR(2000);
ALTER TABLE flow_type ADD  VIEW_PRIV  int;
ALTER TABLE flow_process ADD  VIEW_PRIV  int;
ALTER TABLE flow_run ADD  VIEW_USER  VARCHAR(2000);

CREATE TABLE APP_LOG (
 SEQ_ID int   NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  USER_ID int ,
  [TIME] datetime,
  MODULE VARCHAR(45),
  OPP_ID VARCHAR(45),
  [TYPE] VARCHAR(45),
  REMARK TEXT
);
 
