ALTER TABLE flow_process ADD (CONTROL_MODE VARCHAR2(2000));

ALTER TABLE flow_form_item ADD (LV_COLTYPE VARCHAR2(2000));
ALTER TABLE flow_form_item ADD (LV_COLVALUE VARCHAR2(2000));

ALTER TABLE rms_roll ADD (PRIV_USER VARCHAR2(2000));
ALTER TABLE rms_roll ADD (PRIV_DEPT VARCHAR2(2000));
ALTER TABLE rms_roll ADD (PRIV_ROLE VARCHAR2(2000));

ALTER TABLE rms_file ADD (PRIV_ROLE VARCHAR2(2000));
ALTER TABLE rms_file ADD (PRIV_DEPT VARCHAR2(2000));
ALTER TABLE rms_file ADD (PRIV_USER VARCHAR2(2000));
