DROP TABLE IF EXISTS data_src;
CREATE TABLE data_src (
  SEQ_ID int(11) primary key NOT NULL auto_increment,
  d_name varchar(40) NOT NULL,
  d_desc varchar(200) NOT NULL,
  d_creator varchar(20) NOT NULL,
  d_dept text NOT NULL,
  d_create_time datetime NOT NULL
);
DROP TABLE IF EXISTS FLOW_PRINT_TPL;
CREATE TABLE FLOW_PRINT_TPL(
 SEQ_ID int(11)  primary key NOT NULL auto_increment,
 FLOW_ID int(11),
 T_TYPE varchar(20),
 T_NAME varchar(100),
 CONTENT text,
 FLOW_PRCS varchar(20)
);

CREATE TABLE V_MEET(
  SEQ_ID int(11) primary key NOT NULL auto_increment,
  BEGIN_USER VARCHAR(20),
  CONTENT VARCHAR(500),
  INVITE_USERS VARCHAR(20),
  ADD_TIME DATE,
  vmeet VARCHAR(20),
  vt VARCHAR(20),
  vck VARCHAR(20)
)
;
CREATE TABLE ZL_PPT(
  SEQ_ID  int(11)  primary key NOT NULL auto_increment,
  NAME VARCHAR(100),
  FOLDER VARCHAR(20),
  TOTAL_FRAME int(11),
  ROOMID VARCHAR(20),
  CREATE_DATE VARCHAR(20)
)
;
CREATE TABLE ZL_FILE(
  SEQ_ID  int(11)  primary key NOT NULL auto_increment,
  NAME VARCHAR(100),
  FILE_NAME VARCHAR(100),
  FSIZE VARCHAR(20),
  ROOMID VARCHAR(20),
  CREATE_DATE VARCHAR(20)
)
;


ALTER TABLE flow_form_item ADD COLUMN DATA_TYPE VARCHAR(10) AFTER METADATA_NAME;
ALTER TABLE flow_form_item ADD COLUMN RADIO_CHECK VARCHAR(10) AFTER DATA_TYPE;
ALTER TABLE flow_form_item ADD COLUMN RADIO_FIELD text AFTER RADIO_CHECK;
ALTER TABLE flow_form_item ADD COLUMN DATE_FORMAT  VARCHAR(100) AFTER RADIO_FIELD;
ALTER TABLE flow_form_item ADD COLUMN HIDDEN  VARCHAR(10) AFTER DATE_FORMAT;
UPDATE code_class SET CLASS_DESC='短信提醒类型' where CLASS_NO = 'SMS_REMIND';
DROP TABLE IF EXISTS secure_key;
CREATE TABLE secure_key (
  SEQ_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  KEY_SN TEXT NOT NULL,
  KEY_INFO TEXT NOT NULL,
  PRIMARY KEY (SEQ_ID)
)
ENGINE = InnoDB;
ALTER TABLE rms_file ADD COLUMN FILE_WORD VARCHAR(45) AFTER TURN_COUNT,
 ADD COLUMN FILE_YEAR VARCHAR(45) AFTER FILE_WORD,
 ADD COLUMN ISSUE_NUM VARCHAR(45) AFTER FILE_YEAR;
INSERT INTO code_class (CLASS_NO,CLASS_DESC,SORT_NO,CLASS_LEVEL) VALUES ('FILE_YEAR','公文年号','2','0');
INSERT INTO code_class (CLASS_NO,CLASS_DESC,SORT_NO,CLASS_LEVEL) VALUES ('FILE_WORD','公文字','1','0');
INSERT INTO code_class (CLASS_NO,CLASS_DESC,SORT_NO,CLASS_LEVEL) VALUES ('ISSUE_NUM','公文期号','3','0');

INSERT INTO code_item (CLASS_NO,CLASS_CODE,CLASS_DESC,SORT_NO,CODE) VALUES ('FILE_WORD','3','外发','3',NULL);
INSERT INTO code_item (CLASS_NO,CLASS_CODE,CLASS_DESC,SORT_NO,CODE) VALUES ('ISSUE_NUM','1','1期','1',NULL);
INSERT INTO code_item (CLASS_NO,CLASS_CODE,CLASS_DESC,SORT_NO,CODE) VALUES ('ISSUE_NUM','2','2期','2',NULL);
INSERT INTO code_item (CLASS_NO,CLASS_CODE,CLASS_DESC,SORT_NO,CODE) VALUES ('FILE_WORD','2','港发','2',NULL);
INSERT INTO code_item (CLASS_NO,CLASS_CODE,CLASS_DESC,SORT_NO,CODE) VALUES ('FILE_WORD','1','明林发','1',NULL);
INSERT INTO code_item (CLASS_NO,CLASS_CODE,CLASS_DESC,SORT_NO,CODE) VALUES ('FILE_YEAR','3','2012','3',NULL);
INSERT INTO code_item (CLASS_NO,CLASS_CODE,CLASS_DESC,SORT_NO,CODE) VALUES ('FILE_YEAR','4','2013','4',NULL);
INSERT INTO code_item (CLASS_NO,CLASS_CODE,CLASS_DESC,SORT_NO,CODE) VALUES ('FILE_YEAR','2','2011','2',NULL);

insert into sys_function (MENU_ID , FUNC_NAME , FUNC_CODE ,ICON ,OPEN_FLAG  )
   values ('0230' , '我的视频会议' , '/subsys/oa/vmeet/index.jsp', 'edit.gif' , '0');
