
create table DOC_DOC_FLOW_PROCESS1 as select * from DOC_FLOW_PROCESS;
delete from DOC_FLOW_PROCESS;
commit;

ALTER TABLE DOC_FLOW_PROCESS DROP column PRCS_TO;

ALTER TABLE DOC_FLOW_PROCESS ADD (PRCS_TO VARCHAR2(2000));


alter trigger "TD_OA"."TRG_DOC_FLOW_PROCESS" disable;
insert into DOC_FLOW_PROCESS(DOC_FLOW_PROCESS.SEQ_ID 
, DOC_FLOW_PROCESS.FLOW_SEQ_ID, DOC_FLOW_PROCESS.PRCS_ID , DOC_FLOW_PROCESS.PRCS_NAME , DOC_FLOW_PROCESS.PRCS_USER,DOC_FLOW_PROCESS.PRCS_ITEM , DOC_FLOW_PROCESS.HIDDEN_ITEM 
, DOC_FLOW_PROCESS.PRCS_DEPT , DOC_FLOW_PROCESS.PRCS_PRIV , DOC_FLOW_PROCESS.PRCS_TO
, DOC_FLOW_PROCESS.SET_LEFT ,  DOC_FLOW_PROCESS.SET_TOP ,  DOC_FLOW_PROCESS.PLUGIN , DOC_FLOW_PROCESS.PRCS_ITEM_AUTO
, DOC_FLOW_PROCESS.PRCS_IN , DOC_FLOW_PROCESS.PRCS_OUT , DOC_FLOW_PROCESS.FEEDBACK , DOC_FLOW_PROCESS.PRCS_IN_SET 
, DOC_FLOW_PROCESS.PRCS_OUT_SET , DOC_FLOW_PROCESS.AUTO_TYPE , DOC_FLOW_PROCESS.AUTO_USER_OP 
, DOC_FLOW_PROCESS.AUTO_USER , DOC_FLOW_PROCESS.USER_FILTER , DOC_FLOW_PROCESS.TIME_OUT  , DOC_FLOW_PROCESS.TIME_EXCEPT
, DOC_FLOW_PROCESS.SIGNLOOK , DOC_FLOW_PROCESS.TOP_DEFAULT , DOC_FLOW_PROCESS.USER_LOCK , DOC_FLOW_PROCESS.MAIL_TO 
, DOC_FLOW_PROCESS.SYNC_DEAL , DOC_FLOW_PROCESS.SYNC_DEAL_CHECK , DOC_FLOW_PROCESS.TURN_PRIV , DOC_FLOW_PROCESS.CHILD_FLOW
,DOC_FLOW_PROCESS.GATHER_NODE  ,DOC_FLOW_PROCESS.ALLOW_BACK , DOC_FLOW_PROCESS.ATTACH_PRIV , DOC_FLOW_PROCESS.AUTO_BASE_USER
,DOC_FLOW_PROCESS.CONDITION_DESC , DOC_FLOW_PROCESS.RELATION , DOC_FLOW_PROCESS.REMIND_FLAG , DOC_FLOW_PROCESS.DISP_AIP
, DOC_FLOW_PROCESS.TIME_OUT_TYPE , DOC_FLOW_PROCESS.METADATA_ITEM , DOC_FLOW_PROCESS.EXTEND , DOC_FLOW_PROCESS.EXTEND1 
, DOC_FLOW_PROCESS.AUTO_SELECT_ROLE , DOC_FLOW_PROCESS.DOC_CREATE , DOC_FLOW_PROCESS.DOC_ATTACH_PRIV 
) (SELECT DOC_DOC_FLOW_PROCESS1.SEQ_ID 
, DOC_DOC_FLOW_PROCESS1.FLOW_SEQ_ID, DOC_DOC_FLOW_PROCESS1.PRCS_ID , DOC_DOC_FLOW_PROCESS1.PRCS_NAME , DOC_DOC_FLOW_PROCESS1.PRCS_USER,DOC_DOC_FLOW_PROCESS1.PRCS_ITEM , DOC_DOC_FLOW_PROCESS1.HIDDEN_ITEM 
, DOC_DOC_FLOW_PROCESS1.PRCS_DEPT , DOC_DOC_FLOW_PROCESS1.PRCS_PRIV , DOC_DOC_FLOW_PROCESS1.PRCS_TO
, DOC_DOC_FLOW_PROCESS1.SET_LEFT ,  DOC_DOC_FLOW_PROCESS1.SET_TOP ,  DOC_DOC_FLOW_PROCESS1.PLUGIN , DOC_DOC_FLOW_PROCESS1.PRCS_ITEM_AUTO
, DOC_DOC_FLOW_PROCESS1.PRCS_IN , DOC_DOC_FLOW_PROCESS1.PRCS_OUT , DOC_DOC_FLOW_PROCESS1.FEEDBACK , DOC_DOC_FLOW_PROCESS1.PRCS_IN_SET 
, DOC_DOC_FLOW_PROCESS1.PRCS_OUT_SET , DOC_DOC_FLOW_PROCESS1.AUTO_TYPE , DOC_DOC_FLOW_PROCESS1.AUTO_USER_OP 
, DOC_DOC_FLOW_PROCESS1.AUTO_USER , DOC_DOC_FLOW_PROCESS1.USER_FILTER , DOC_DOC_FLOW_PROCESS1.TIME_OUT  , DOC_DOC_FLOW_PROCESS1.TIME_EXCEPT
, DOC_DOC_FLOW_PROCESS1.SIGNLOOK , DOC_DOC_FLOW_PROCESS1.TOP_DEFAULT , DOC_DOC_FLOW_PROCESS1.USER_LOCK , DOC_DOC_FLOW_PROCESS1.MAIL_TO 
, DOC_DOC_FLOW_PROCESS1.SYNC_DEAL , DOC_DOC_FLOW_PROCESS1.SYNC_DEAL_CHECK , DOC_DOC_FLOW_PROCESS1.TURN_PRIV , DOC_DOC_FLOW_PROCESS1.CHILD_FLOW
,DOC_DOC_FLOW_PROCESS1.GATHER_NODE  ,DOC_DOC_FLOW_PROCESS1.ALLOW_BACK , DOC_DOC_FLOW_PROCESS1.ATTACH_PRIV , DOC_DOC_FLOW_PROCESS1.AUTO_BASE_USER
,DOC_DOC_FLOW_PROCESS1.CONDITION_DESC , DOC_DOC_FLOW_PROCESS1.RELATION , DOC_DOC_FLOW_PROCESS1.REMIND_FLAG , DOC_DOC_FLOW_PROCESS1.DISP_AIP
, DOC_DOC_FLOW_PROCESS1.TIME_OUT_TYPE , DOC_DOC_FLOW_PROCESS1.METADATA_ITEM , DOC_DOC_FLOW_PROCESS1.EXTEND , DOC_DOC_FLOW_PROCESS1.EXTEND1 
, DOC_DOC_FLOW_PROCESS1.AUTO_SELECT_ROLE , DOC_DOC_FLOW_PROCESS1.DOC_CREATE , DOC_DOC_FLOW_PROCESS1.DOC_ATTACH_PRIV  FROM DOC_DOC_FLOW_PROCESS1);
alter trigger "TD_OA"."TRG_DOC_FLOW_PROCESS" enable;