alter table news ALTER COLUMN ATTACHMENT_ID NVARCHAR(3000) ;
alter table news ALTER COLUMN ATTACHMENT_NAME NVARCHAR(3000) ;
alter table news ALTER COLUMN SUBJECT NVARCHAR(500) ;
alter table news ALTER COLUMN [USER_ID] NVARCHAR(3000) ;
alter table news ALTER COLUMN PRIV_ID NVARCHAR(3000) ;
alter table news ALTER COLUMN TO_ID NVARCHAR(3000) ;
alter table news ALTER COLUMN READERS ntext ;
