--第一步
create table FLOW_PROCESS1 as select * from FLOW_PROCESS;
delete from FLOW_PROCESS;
commit;
--第二步
ALTER TABLE FLOW_PROCESS DROP column PRCS_TO;

ALTER TABLE FLOW_PROCESS ADD (PRCS_TO VARCHAR2(2000));

--第三步
alter trigger "TD_OA"."TRG_FLOW_PROCESS" disable;
insert into FLOW_PROCESS(FLOW_PROCESS.SEQ_ID 
, FLOW_PROCESS.FLOW_SEQ_ID, FLOW_PROCESS.PRCS_ID , FLOW_PROCESS.PRCS_NAME , FLOW_PROCESS.PRCS_USER,FLOW_PROCESS.PRCS_ITEM , FLOW_PROCESS.HIDDEN_ITEM 
, FLOW_PROCESS.PRCS_DEPT , FLOW_PROCESS.PRCS_PRIV , FLOW_PROCESS.PRCS_TO
, FLOW_PROCESS.SET_LEFT ,  FLOW_PROCESS.SET_TOP ,  FLOW_PROCESS.PLUGIN , FLOW_PROCESS.PRCS_ITEM_AUTO
, FLOW_PROCESS.PRCS_IN , FLOW_PROCESS.PRCS_OUT , FLOW_PROCESS.FEEDBACK , FLOW_PROCESS.PRCS_IN_SET 
, FLOW_PROCESS.PRCS_OUT_SET , FLOW_PROCESS.AUTO_TYPE , FLOW_PROCESS.AUTO_USER_OP 
, FLOW_PROCESS.AUTO_USER , FLOW_PROCESS.USER_FILTER , FLOW_PROCESS.TIME_OUT  , FLOW_PROCESS.TIME_EXCEPT
, FLOW_PROCESS.SIGNLOOK , FLOW_PROCESS.TOP_DEFAULT , FLOW_PROCESS.USER_LOCK , FLOW_PROCESS.MAIL_TO 
, FLOW_PROCESS.SYNC_DEAL , FLOW_PROCESS.SYNC_DEAL_CHECK , FLOW_PROCESS.TURN_PRIV , FLOW_PROCESS.CHILD_FLOW
,FLOW_PROCESS.GATHER_NODE  ,FLOW_PROCESS.ALLOW_BACK , FLOW_PROCESS.ATTACH_PRIV , FLOW_PROCESS.AUTO_BASE_USER
,FLOW_PROCESS.CONDITION_DESC , FLOW_PROCESS.RELATION , FLOW_PROCESS.REMIND_FLAG , FLOW_PROCESS.DISP_AIP
, FLOW_PROCESS.TIME_OUT_TYPE , FLOW_PROCESS.METADATA_ITEM , FLOW_PROCESS.EXTEND , FLOW_PROCESS.EXTEND1 
, FLOW_PROCESS.AUTO_SELECT_ROLE , FLOW_PROCESS.DOC_CREATE , FLOW_PROCESS.DOC_ATTACH_PRIV 
) (SELECT FLOW_PROCESS1.SEQ_ID 
, FLOW_PROCESS1.FLOW_SEQ_ID, FLOW_PROCESS1.PRCS_ID , FLOW_PROCESS1.PRCS_NAME , FLOW_PROCESS1.PRCS_USER,FLOW_PROCESS1.PRCS_ITEM , FLOW_PROCESS1.HIDDEN_ITEM 
, FLOW_PROCESS1.PRCS_DEPT , FLOW_PROCESS1.PRCS_PRIV , FLOW_PROCESS1.PRCS_TO
, FLOW_PROCESS1.SET_LEFT ,  FLOW_PROCESS1.SET_TOP ,  FLOW_PROCESS1.PLUGIN , FLOW_PROCESS1.PRCS_ITEM_AUTO
, FLOW_PROCESS1.PRCS_IN , FLOW_PROCESS1.PRCS_OUT , FLOW_PROCESS1.FEEDBACK , FLOW_PROCESS1.PRCS_IN_SET 
, FLOW_PROCESS1.PRCS_OUT_SET , FLOW_PROCESS1.AUTO_TYPE , FLOW_PROCESS1.AUTO_USER_OP 
, FLOW_PROCESS1.AUTO_USER , FLOW_PROCESS1.USER_FILTER , FLOW_PROCESS1.TIME_OUT  , FLOW_PROCESS1.TIME_EXCEPT
, FLOW_PROCESS1.SIGNLOOK , FLOW_PROCESS1.TOP_DEFAULT , FLOW_PROCESS1.USER_LOCK , FLOW_PROCESS1.MAIL_TO 
, FLOW_PROCESS1.SYNC_DEAL , FLOW_PROCESS1.SYNC_DEAL_CHECK , FLOW_PROCESS1.TURN_PRIV , FLOW_PROCESS1.CHILD_FLOW
,FLOW_PROCESS1.GATHER_NODE  ,FLOW_PROCESS1.ALLOW_BACK , FLOW_PROCESS1.ATTACH_PRIV , FLOW_PROCESS1.AUTO_BASE_USER
,FLOW_PROCESS1.CONDITION_DESC , FLOW_PROCESS1.RELATION , FLOW_PROCESS1.REMIND_FLAG , FLOW_PROCESS1.DISP_AIP
, FLOW_PROCESS1.TIME_OUT_TYPE , FLOW_PROCESS1.METADATA_ITEM , FLOW_PROCESS1.EXTEND , FLOW_PROCESS1.EXTEND1 
, FLOW_PROCESS1.AUTO_SELECT_ROLE , FLOW_PROCESS1.DOC_CREATE , FLOW_PROCESS1.DOC_ATTACH_PRIV  FROM FLOW_PROCESS1);
alter trigger "TD_OA"."TRG_FLOW_PROCESS" enable;

drop table FLOW_PROCESS1;