CREATE TABLE APP_LOG (
  SEQ_ID NUMBER primary key,
  USER_ID NUMBER,
  TIME DATE,
  MODULE  VARCHAR2(45),
  OPP_ID VARCHAR2(45),
  TYPE VARCHAR2(45),
  REMARK  CLOB
);
exec pr_CreateIdentityColumn('APP_LOG','SEQ_ID');
ALTER TABLE flow_type ADD (VIEW_USER VARCHAR2(2000));
ALTER TABLE flow_type ADD (VIEW_PRIV NUMBER);
ALTER TABLE flow_process ADD (VIEW_PRIV NUMBER);
ALTER TABLE flow_run ADD (VIEW_USER VARCHAR2(2000));