ALTER TABLE flow_process ADD CONTROL_MODE VARCHAR(2000);
ALTER TABLE flow_form_item ADD LV_COLTYPE VARCHAR(2000);
ALTER TABLE flow_form_item ADD LV_COLVALUE VARCHAR(2000);

ALTER TABLE rms_roll ADD PRIV_USER VARCHAR(2000);
ALTER TABLE rms_roll ADD PRIV_DEPT VARCHAR(2000);
ALTER TABLE rms_roll ADD PRIV_ROLE VARCHAR(2000);
ALTER TABLE rms_file ADD PRIV_USER VARCHAR(2000);
ALTER TABLE rms_file ADD PRIV_DEPT VARCHAR(2000);
ALTER TABLE rms_file ADD PRIV_ROLE VARCHAR(2000);

